name: ferm
on: push
jobs:
  build_pkg:
    uses: gardenlinux/package-build/.github/workflows/build_pkg.yml@main
    with:
      source: git+https://github.com/MaxKellermann/ferm
      debian_source: ferm
      git_filter: v[0-9\.]*$
      git_tag_match: v([0-9\-]*)
